/* generated from web/index.html - do not edit */
#include "common.h"
const char g_index_html[] =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"theme-color\" content=\"#08080b\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,viewport-fit=cover\">\n"
"<title>Game Library Manager</title>\n"
"<style>\n"
":root{\n"
"  --bg:#08080b;--side:#0f0f13;--panel:#15151b;--panel2:#1d1d25;--line:rgba(255,255,255,.09);--line2:"
"rgba(255,255,255,.16);\n"
"  --text:#f2f4f8;--body:#c9d0da;--dim:#8f98a6;--accent:#1a8cff;--accent2:#5aaeff;--ok:#3ccf6e;--warn"
":#f0b23c;--bad:#ff6b63;\n"
"  --r:18px;--r2:12px;--side-w:270px;\n"
"}\n"
"*{box-sizing:border-box}\n"
"html{font-size:16px}\n"
"@media (min-width:1200px){html{font-size:18px}}\n"
"@media (min-width:1700px){html{font-size:20px}}\n"
"html,body{margin:0;background:var(--bg);color:var(--text);\n"
"  font:1rem/1.5 \"Inter\",-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Helvetica,Arial,sans-"
"serif;-webkit-font-smoothing:antialiased}\n"
".app{min-height:100vh}\n"
"/* sidebar */\n"
".nav{position:fixed;top:0;left:0;bottom:0;width:var(--side-w);background:var(--side);border-right:1p"
"x solid var(--line);\n"
"  display:flex;flex-direction:column;padding:22px 14px;z-index:8}\n"
".brand{display:flex;align-items:center;gap:12px;padding:4px 10px 22px}\n"
".logo{width:44px;height:44px;border-radius:13px;background:linear-gradient(135deg,#1a8cff,#7a5cff);d"
"isplay:grid;place-items:center;\n"
"  font-weight:800;font-size:1.05rem;letter-spacing:.5px;flex:none}\n"
".brand b{display:block;font-size:1.05rem;line-height:1.2}\n"
".brand span{color:var(--dim);font-size:.85rem}\n"
".nav nav{display:flex;flex-direction:column;gap:4px}\n"
".nav-item{display:flex;align-items:center;gap:12px;width:100%;text-align:left;background:none;border"
":1px solid transparent;\n"
"  color:var(--body);font:inherit;font-size:1rem;font-weight:600;padding:12px 14px;border-radius:var("
"--r2);cursor:pointer;min-height:52px}\n"
".nav-item svg{width:22px;height:22px;flex:none;opacity:.85}\n"
".nav-item:hover{background:var(--panel)}\n"
".nav-item.on{background:rgba(26,140,255,.14);color:#fff;border-color:rgba(26,140,255,.35)}\n"
".nav-item.on svg{color:var(--accent2);opacity:1}\n"
".nbadge{margin-left:auto;font-size:.8rem;font-weight:700;min-width:28px;text-align:center;padding:2p"
"x 9px;border-radius:999px;background:var(--panel2);color:var(--body)}\n"
".nbadge:empty{display:none}\n"
".nbadge.warn{background:rgba(240,178,60,.18);color:var(--warn)}\n"
".nbadge.live{background:rgba(26,140,255,.2);color:var(--accent2)}\n"
".nav-foot{margin-top:auto;display:flex;flex-direction:column;gap:10px;padding:10px 6px 0}\n"
".ver{color:var(--dim);font-size:.8rem;text-align:center}\n"
"/* content */\n"
"main{margin-left:var(--side-w);padding:34px 48px 140px}\n"
".vhead{display:flex;align-items:flex-start;gap:16px;flex-wrap:wrap;margin-bottom:22px}\n"
".vhead h1{font-size:2rem;line-height:1.15;margin:0 0 6px;font-weight:800;letter-spacing:-.3px;displa"
"y:flex;align-items:center;gap:12px}\n"
".vhead p{margin:0;color:var(--body);font-size:1.05rem;max-width:70ch}\n"
".vhead .actions{margin-left:auto;display:flex;gap:10px;flex-wrap:wrap}\n"
".count{font-size:.9rem;font-weight:700;background:var(--panel2);color:var(--body);border-radius:999p"
"x;padding:3px 12px;letter-spacing:0}\n"
"h2.sub{font-size:1.2rem;margin:30px 0 12px;font-weight:700}\n"
".view[hidden]{display:none}\n"
"/* controls */\n"
"button,select{font:inherit;font-size:.95rem;font-weight:600;color:var(--text);background:var(--panel"
"2);border:1px solid var(--line2);\n"
"  border-radius:var(--r2);padding:12px 20px;min-height:50px;cursor:pointer}\n"
"button:hover{border-color:rgba(255,255,255,.3)}\n"
"button.primary{background:var(--accent);border-color:var(--accent);color:#fff}\n"
"button.primary:hover{background:#3399ff}\n"
"button.danger{color:var(--bad)}\n"
"button.small{padding:8px 15px;min-height:42px;font-size:.9rem}\n"
"button:disabled{opacity:.4;cursor:default}\n"
"button:focus-visible,select:focus-visible,input:focus-visible,label.lib-item:focus-within,.stat:focu"
"s-visible{outline:3px solid var(--accent2);outline-offset:3px}\n"
"/* cards */\n"
".card{border:1px solid var(--line);background:var(--panel);border-radius:var(--r);padding:18px 20px;"
"margin:12px 0}\n"
".row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}\n"
".spacer{flex:1}\n"
".title{font-weight:700;font-size:1.1rem}\n"
".tid{color:var(--dim);font-size:.85rem;font-family:ui-monospace,Menlo,Consolas,monospace}\n"
".path{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:.82rem;color:var(--dim);word-break"
":break-all;margin-top:4px}\n"
".arrow{color:var(--accent2);font-family:ui-monospace,Menlo,Consolas,monospace;font-size:.85rem;word-"
"break:break-all;margin-top:4px}\n"
".detail{font-size:.95rem;margin:8px 0;color:var(--body)}\n"
".explain{font-size:.95rem;color:var(--body);margin:4px 0 12px;max-width:75ch}\n"
".badge{font-size:.72rem;font-weight:700;padding:3px 9px;border-radius:7px;background:var(--panel2);b"
"order:1px solid var(--line2);color:var(--body);text-transform:uppercase;letter-spacing:.5px}\n"
".empty{color:var(--body);padding:22px;text-align:center;background:var(--panel);border:1px dashed va"
"r(--line2);border-radius:var(--r)}\n"
".st-ok{color:var(--ok)}.st-warn{color:var(--warn)}.st-bad{color:var(--bad)}\n"
".bar{height:8px;background:rgba(255,255,255,.08);border-radius:99px;overflow:hidden;margin:12px 0 6p"
"x}\n"
".bar>i{display:block;height:100%;background:var(--accent);border-radius:99px;transition:width .5s}\n"
".stats{display:flex;gap:18px;flex-wrap:wrap;font-size:.9rem;color:var(--dim)}\n"
".stats b{color:var(--text);font-weight:700}\n"
"/* overview */\n"
".stat-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:18px}\n"
".stat{background:var(--panel);border:1px solid var(--line);border-radius:var(--r);padding:20px 22px;"
"text-align:left;font:inherit;color:inherit;\n"
"  cursor:pointer;min-height:150px;display:flex;flex-direction:column;gap:6px;transition:border-color"
" .2s,transform .2s}\n"
".stat:hover{border-color:var(--accent);transform:translateY(-2px)}\n"
".stat .lab{color:var(--dim);font-size:.8rem;font-weight:700;text-transform:uppercase;letter-spacing:"
".8px}\n"
".stat .big{font-size:2.3rem;font-weight:800;line-height:1.1}\n"
".stat .note{color:var(--body);font-size:.92rem}\n"
".drives{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:18px}\n"
".drive{background:var(--panel);border:1px solid var(--line);border-radius:var(--r);padding:18px 20px"
"}\n"
".drive .title{font-size:1.1rem}\n"
"/* library */\n"
".lib-item{display:flex;gap:14px;align-items:flex-start;padding:14px 4px;border-top:1px solid var(--l"
"ine);cursor:pointer}\n"
".lib-item:first-child{border-top:0}\n"
".lib-item input{width:26px;height:26px;margin-top:2px;flex:none;accent-color:var(--accent)}\n"
".lib-item .grow{flex:1;min-width:0}\n"
".drive-head{margin:22px 0 8px;color:var(--body);font-size:.95rem;font-weight:700}\n"
".libcard{background:var(--panel);border:1px solid var(--line);border-radius:var(--r);padding:4px 20p"
"x}\n"
".job-done{color:var(--ok)}.job-fail{color:var(--bad)}\n"
".pill{font-size:.85rem;font-weight:700;padding:6px 12px;border-radius:999px;background:var(--panel2)"
";border:1px solid var(--line2);color:var(--body);text-align:center}\n"
".pill.ok{color:var(--ok);border-color:rgba(60,207,110,.35);background:rgba(60,207,110,.08)}\n"
".pill.bad{color:var(--bad);border-color:rgba(255,107,99,.35);background:rgba(255,107,99,.08)}\n"
".pill.warn{color:var(--warn);border-color:rgba(240,178,60,.35);background:rgba(240,178,60,.08)}\n"
"details summary{cursor:pointer;color:var(--body);font-size:.9rem;padding:6px 0}\n"
".banner{border-radius:var(--r);padding:16px 20px;margin:0 0 22px;border:1px solid;font-size:1rem}\n"
".banner.warn{background:#241c0c;border-color:#5c4518;color:#ffd27a}\n"
".banner.bad{background:#2a1212;border-color:#6a2a27;color:#ffb3ae}\n"
".banner .head{display:block;margin-bottom:4px;font-weight:800}\n"
".fixstate{font-size:.95rem;font-weight:700}\n"
"code{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:.85em;background:rgba(255,255,255,."
"07);padding:2px 6px;border-radius:6px}\n"
".setting{background:var(--panel);border:1px solid var(--line);border-radius:var(--r);padding:20px 22"
"px;margin:0 0 16px}\n"
".setting h3{margin:0 0 6px;font-size:1.2rem}\n"
".setting select{min-width:min(100%,420px)}\n"
"#batch{position:fixed;left:var(--side-w);right:0;bottom:0;z-index:7;background:rgba(15,15,19,.97);bo"
"rder-top:1px solid var(--line2);\n"
"  padding:14px 44px;display:none}\n"
"#batch .inner{max-width:1180px;display:flex;gap:10px;align-items:center;flex-wrap:wrap}\n"
"#toast{position:fixed;left:50%;top:24px;transform:translateX(-50%);background:#22222b;border:1px sol"
"id var(--line2);\n"
"  border-radius:var(--r2);padding:14px 20px;z-index:30;display:none;max-width:90vw;font-weight:600}\n"
"/* guide */\n"
"#guide{position:fixed;left:0;right:0;bottom:0;z-index:20;display:none;padding:0 12px calc(12px + env"
"(safe-area-inset-bottom))}\n"
"#guide .sheet{max-width:640px;margin:0 auto;background:#17171f;border:1px solid rgba(26,140,255,.45)"
";border-radius:20px;\n"
"  box-shadow:0 10px 50px rgba(0,0,0,.7);padding:22px 24px;max-height:56vh;overflow:auto}\n"
"#guide .step{font-size:.8rem;font-weight:700;color:var(--accent2);text-transform:uppercase;letter-sp"
"acing:1px}\n"
"#guide h3{margin:6px 0 8px;font-size:1.45rem;line-height:1.2}\n"
"#guide p{margin:8px 0;font-size:1rem;color:var(--body)}\n"
"#guide ul{margin:8px 0;padding-left:22px;font-size:1rem;color:var(--body)}\n"
"#guide li{margin:6px 0}\n"
"#guide b{color:var(--text)}\n"
"#guide .live{margin:12px 0;padding:12px 14px;border-radius:var(--r2);background:#0c0c11;border:1px s"
"olid var(--line);font-size:1rem;color:var(--body)}\n"
"#guide .live:empty{display:none}\n"
"#guide .dots{display:flex;gap:6px;margin:14px 0 4px}\n"
"#guide .dots i{width:9px;height:9px;border-radius:50%;background:rgba(255,255,255,.15)}\n"
"#guide .dots i.on{background:var(--accent)}\n"
"#guide .nav2{display:flex;gap:10px;align-items:center;margin-top:12px}\n"
".guide-hi{outline:3px solid var(--accent)!important;outline-offset:4px;border-radius:var(--r)}\n"
"body.guiding main{padding-bottom:62vh}\n"
"body.guiding #batch{display:none!important}\n"
"@media (min-width:1200px){\n"
"  #guide{left:auto;right:28px;bottom:28px;top:auto;width:460px;padding:0}\n"
"  #guide .sheet{max-height:calc(100vh - 56px)}\n"
"  body.guiding main{padding-right:520px;padding-bottom:140px}\n"
"}\n"
".topbar{display:none;align-items:center;gap:10px;margin-bottom:16px}\n"
".topbar .logo{width:36px;height:36px;font-size:.9rem;border-radius:11px}\n"
".topbar b{font-size:1.05rem}\n"
"/* phones: bottom tab bar */\n"
"@media (max-width:899px){\n"
"  .nav{top:auto;right:0;width:auto;height:auto;flex-direction:row;padding:6px 6px calc(6px + env(saf"
"e-area-inset-bottom));border-right:0;border-top:1px solid var(--line2)}\n"
"  .brand,.nav-foot{display:none}\n"
"  .nav nav{flex-direction:row;width:100%;gap:2px}\n"
"  .nav-item{flex:1;flex-direction:column;gap:3px;padding:6px 2px;font-size:.68rem;min-height:56px;te"
"xt-align:center;position:relative}\n"
"  .nav-item .lbl-long{display:none}\n"
"  .nbadge{position:absolute;top:2px;right:6px;margin:0;font-size:.65rem;padding:1px 6px;min-width:0}"
"\n"
"  main{margin-left:0;padding:16px 16px 120px}\n"
"  .topbar{display:flex}\n"
"  .vhead h1{font-size:1.6rem}\n"
"  #batch{left:0;bottom:70px;padding:10px 16px}\n"
"  #guide{bottom:72px}\n"
"  body.guiding main{padding-bottom:70vh}\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div class=\"app\">\n"
"<aside class=\"nav\">\n"
"  <div class=\"brand\"><div class=\"logo\">GL</div><div><b>Game Library</b><span>Manager</span></div"
"></div>\n"
"  <nav>\n"
"    <button class=\"nav-item\" data-view=\"home\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\""
"currentColor\" stroke-width=\"2\"><rect x=\"3\" y=\"3\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect x"
"=\"14\" y=\"3\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect x=\"3\" y=\"14\" width=\"7\" height=\"7\""
" rx=\"1.5\"/><rect x=\"14\" y=\"14\" width=\"7\" height=\"7\" rx=\"1.5\"/></svg><span>Overview</span"
"></button>\n"
"    <button class=\"nav-item\" data-view=\"attention\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stro"
"ke=\"currentColor\" stroke-width=\"2\"><path d=\"M12 3 2 20h20L12 3z\"/><path d=\"M12 10v4M12 17.5v."
"5\"/></svg><span>Needs <span class=\"lbl-long\">attention</span></span><span id=\"navAttn\" class=\""
"nbadge\"></span></button>\n"
"    <button class=\"nav-item\" data-view=\"library\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke"
"=\"currentColor\" stroke-width=\"2\"><rect x=\"3\" y=\"4\" width=\"5\" height=\"16\" rx=\"1\"/><rect"
" x=\"10\" y=\"4\" width=\"5\" height=\"16\" rx=\"1\"/><path d=\"m17 5 4 1-3 14-4-1z\"/></svg><span>L"
"ibrary</span><span id=\"navLib\" class=\"nbadge\"></span></button>\n"
"    <button class=\"nav-item\" data-view=\"queue\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\""
"currentColor\" stroke-width=\"2\"><path d=\"M4 6h16M4 12h16M4 18h10\"/></svg><span>Queue</span><span"
" id=\"navQ\" class=\"nbadge\"></span></button>\n"
"    <button class=\"nav-item\" data-view=\"savefix\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke"
"=\"currentColor\" stroke-width=\"2\"><path d=\"M5 3h11l3 3v15H5z\"/><path d=\"M8 3v6h8V3M8 21v-7h8v7"
"\"/></svg><span>Save fix</span><span id=\"navSf\" class=\"nbadge\"></span></button>\n"
"    <button class=\"nav-item\" data-view=\"settings\"><svg viewBox=\"0 0 24 24\" fill=\"none\" strok"
"e=\"currentColor\" stroke-width=\"2\"><circle cx=\"12\" cy=\"12\" r=\"3.2\"/><path d=\"M12 2v3M12 19"
"v3M2 12h3M19 12h3M4.9 4.9 7 7M17 17l2.1 2.1M4.9 19.1 7 17M17 7l2.1-2.1\"/></svg><span>Settings</span"
"></button>\n"
"  </nav>\n"
"  <div class=\"nav-foot\">\n"
"    <span id=\"smpPill\" class=\"pill\">ShadowMount \342\200\246</span>\n"
"    <button id=\"guideBtn\" class=\"small\">Show the guide</button>\n"
"    <div class=\"ver\" id=\"verTxt\"></div>\n"
"  </div>\n"
"</aside>\n"
"\n"
"<main>\n"
"  <div class=\"topbar\"><div class=\"logo\">GL</div><b>Game Library Manager</b><span class=\"spacer\""
"></span><button id=\"guideBtn2\" class=\"small\">Guide</button></div>\n"
"  <div id=\"smpBanner\"></div>\n"
"\n"
"  <section class=\"view\" data-view=\"home\" id=\"homeSec\">\n"
"    <div class=\"vhead\"><div><h1>Overview</h1><p>Your games across every drive, and anything Shadow"
"Mount Plus can't see yet.</p></div>\n"
"      <div class=\"actions\"><button id=\"scanBtn\" class=\"primary\">Rescan drives</button></div></"
"div>\n"
"    <div class=\"stat-grid\" id=\"homeStats\"></div>\n"
"    <h2 class=\"sub\">Drives</h2>\n"
"    <div id=\"driveSec\"><div id=\"drives\" class=\"drives\"></div></div>\n"
"  </section>\n"
"\n"
"  <section class=\"view\" data-view=\"attention\" id=\"probSec\" hidden>\n"
"    <div class=\"vhead\"><div><h1>Needs attention <span id=\"pCount\" class=\"count\">0</span></h1>\n"
"      <p>Games ShadowMount won't pick up, why, and where they should go. Nothing moves until you pre"
"ss a button.</p></div>\n"
"      <div class=\"actions\"><button id=\"fixAllBtn\" class=\"primary\" disabled>Fix all</button></d"
"iv></div>\n"
"    <div id=\"problems\"><div class=\"empty\">Scanning\342\200\246</div></div>\n"
"  </section>\n"
"\n"
"  <section class=\"view\" data-view=\"library\" id=\"libSec\" hidden>\n"
"    <div class=\"vhead\"><div><h1>Library <span id=\"lCount\" class=\"count\">0</span></h1>\n"
"      <p>Every game on every drive. Tick games, pick a drive in the bar at the bottom, then press Mo"
"ve.</p></div></div>\n"
"    <div id=\"library\"></div>\n"
"  </section>\n"
"\n"
"  <section class=\"view\" data-view=\"queue\" id=\"queueSec\" hidden>\n"
"    <div class=\"vhead\"><div><h1>Queue <span id=\"qCount\" class=\"count\">0</span></h1>\n"
"      <p>Moves, fixes and extractions run here one at a time in the background. You can close this p"
"age.</p></div>\n"
"      <div class=\"actions\"><button id=\"pauseBtn\" class=\"small\">Pause</button><button id=\"stop"
"Btn\" class=\"small danger\">Stop batch</button><button id=\"clearBtn\" class=\"small\">Clear finish"
"ed</button></div></div>\n"
"    <div id=\"queue\"><div class=\"empty\">Nothing queued.</div></div>\n"
"  </section>\n"
"\n"
"  <section class=\"view\" data-view=\"savefix\" id=\"saveSec\" hidden>\n"
"    <div class=\"vhead\"><div><h1>Save fix <span id=\"sfCount\" class=\"count\">0</span></h1>\n"
"      <p>For backported games that won't save.</p></div>\n"
"      <div class=\"actions\"><button id=\"sfAllBtn\" class=\"primary\" disabled>Apply to all</button"
"></div></div>\n"
"    <div id=\"fakelib\"></div>\n"
"  </section>\n"
"\n"
"  <section class=\"view\" data-view=\"settings\" id=\"setSec\" hidden>\n"
"    <div class=\"vhead\"><div><h1>Settings</h1><p>ShadowMount's scan depth, the home-screen tile and"
" phone notifications.</p></div></div>\n"
"    <div class=\"setting\" id=\"depthLbl\"><h3>ShadowMount scan depth</h3>\n"
"      <div class=\"explain\">How many folder levels ShadowMount looks into. This is saved in ShadowM"
"ount's own settings, and Needs attention follows it.</div>\n"
"      <select id=\"depthSel\"><option value=\"1\">1 \342\200\223 only games directly inside homebrew"
"</option><option value=\"2\">2 \342\200\223 also one subfolder deeper</option></select></div>\n"
"    <div class=\"setting\" id=\"tileSec\"><h3>Home tile</h3><div id=\"tile\"></div></div>\n"
"    <div class=\"setting\" id=\"pushSec\"><h3>Notifications</h3><div id=\"push\"></div></div>\n"
"  </section>\n"
"</main>\n"
"</div>\n"
"\n"
"<div id=\"batch\"><div class=\"inner\">\n"
"  <b id=\"selCount\">0 selected</b>\n"
"  <select id=\"dest\"></select>\n"
"  <button id=\"moveBtn\" class=\"primary\">Move</button>\n"
"  <button id=\"copyBtn\">Copy</button>\n"
"  <button id=\"selNone\" class=\"small\">Clear</button>\n"
"</div></div>\n"
"<div id=\"toast\"></div>\n"
"<div id=\"guide\" role=\"dialog\" aria-labelledby=\"gTitle\"><div class=\"sheet\">\n"
"  <div class=\"step\" id=\"gStep\"></div>\n"
"  <h3 id=\"gTitle\"></h3>\n"
"  <div id=\"gBody\"></div>\n"
"  <div class=\"live\" id=\"gLive\"></div>\n"
"  <div class=\"dots\" id=\"gDots\"></div>\n"
"  <div class=\"nav2\"><button id=\"gSkip\" class=\"small\">Skip guide</button><span class=\"spacer\""
"></span>\n"
"    <button id=\"gBack\" class=\"small\">Back</button><button id=\"gNext\" class=\"primary\">Next</b"
"utton></div>\n"
"</div></div>\n"
"\n"
"<script>\n"
"const $ = s => document.querySelector(s);\n"
"const esc = s => String(s \?\? \"\").replace(/[&<>\"']/g, c => ({\"&\":\"&amp;\",\"<\":\"&lt;\",\">\""
":\"&gt;\",'\"':\"&quot;\",\"'\":\"&#39;\"}[c]));\n"
"const sel = new Set();\n"
"let state = null, lastProg = {}, speeds = {};\n"
"\n"
"function fmtBytes(b){ if(!b) return \"0 B\"; const u=[\"B\",\"KB\",\"MB\",\"GB\",\"TB\"]; let i=0; w"
"hile(b>=1024&&i<4){b/=1024;i++} return (i\?b.toFixed(1):b)+\" \"+u[i]; }\n"
"function fmtTime(s){ s=Math.max(0,Math.round(s)); const h=Math.floor(s/3600), m=Math.floor(s%3600/60"
"), x=s%60;\n"
"  if(h) return h+\" hours \"+m+\" minutes\"; if(m) return m+\" minutes \"+x+\" seconds\"; return x+\""
" seconds\"; }\n"
"function toast(msg){ const t=$(\"#toast\"); t.textContent=msg; t.style.display=\"block\"; clearTimeo"
"ut(toast.t); toast.t=setTimeout(()=>t.style.display=\"none\",3500); }\n"
"\n"
"async function post(path){\n"
"  try{ const r = await fetch(path,{method:\"POST\"}); const j = await r.json(); toast(j.message||\"O"
"K\"); refresh(); return j.ok; }\n"
"  catch(e){ toast(\"Couldn't reach the PS5\"); return false; }\n"
"}\n"
"\n"
"function gsize(g){ return g.size_state===0\? 'measuring\342\200\246' : (g.size_state===2\? '\342\211"
"\245 ':'')+fmtBytes(g.size); }\n"
"function gameName(g){ return g.title || g.title_id || g.path.split(\"/\").pop(); }\n"
"function driveLabel(m){ const d=(state\?.scan.drives||[]).find(x=>x.mount===m); return d\? d.label+\""
" (\"+m+\")\" : m; }\n"
"\n"
"function renderHeader(s){\n"
"  const p=$(\"#smpPill\");\n"
"  const st=s.scan.smp_status;\n"
"  const labels={ok:\"ShadowMount \"+(s.scan.smp_version||\"\")+\" connected\", not_installed:\"SMP n"
"ot installed\", api_disabled:\"SMP API switched off\",\n"
"    no_api:\"SMP not found / older than 1.7\", too_old:\"SMP \"+(s.scan.smp_version||\"\")+\" too ol"
"d\", missing_features:\"SMP needs updating\"};\n"
"  p.className=\"pill \"+(st===\"ok\"\?\"ok\":(st===\"not_installed\"||st===\"too_old\")\?\"bad\":\"w"
"arn\");\n"
"  p.textContent=labels[st]||\"SMP \342\200\246\";\n"
"  const ban=$(\"#smpBanner\");\n"
"  if(st && st!==\"ok\"){\n"
"    ban.innerHTML=`<div class=\"banner ${st===\"not_installed\"||st===\"too_old\"\?\"bad\":\"warn\"}"
"\"><span class=\"head\">${esc(labels[st])}</span>${esc(s.scan.smp_message)}\n"
"      <div style=\"margin-top:6px\">Game Library Manager needs <b>ShadowMount Plus 1.7 or newer</b> "
"for the \"does SMP see it\?\" checks. Finding, fixing and moving games still work.</div></div>`;\n"
"  } else ban.innerHTML=\"\";\n"
"  const ds=$(\"#depthSel\"); if(document.activeElement!==ds) ds.value=String(s.scan.depth);\n"
"  $(\"#scanBtn\").textContent = s.scan.running \? \"Scanning\342\200\246\" : s.scan.sizing \? \"Meas"
"uring sizes\342\200\246\" : \"Rescan drives\";\n"
"  $(\"#verTxt\").textContent = \"Version \"+s.version;\n"
"  const probs=s.scan.games.filter(g=>g.issue!==\"ok\").length, act=s.queue.jobs.filter(j=>j.state==="
"\"queued\"||j.state===\"running\").length,\n"
"        sfn=s.scan.games.filter(g=>g.savefix===1).length;\n"
"  $(\"#navAttn\").textContent=probs||\"\"; $(\"#navAttn\").className=\"nbadge\"+(probs\?\" warn\":\""
"\");\n"
"  $(\"#navLib\").textContent=s.scan.games.filter(g=>g.issue===\"ok\").length||\"\";\n"
"  $(\"#navQ\").textContent=act||\"\"; $(\"#navQ\").className=\"nbadge\"+(act\?\" live\":\"\");\n"
"  $(\"#navSf\").textContent=sfn||\"\"; $(\"#navSf\").className=\"nbadge\"+(sfn\?\" warn\":\"\");\n"
"  renderHome(s);\n"
"  $(\"#scanBtn\").disabled = s.scan.running;\n"
"}\n"
"\n"
"function renderHome(s){\n"
"  const sc=s.scan, st=sc.smp_status, probs=sc.games.filter(g=>g.issue!==\"ok\"), ok=sc.games.filter("
"g=>g.issue===\"ok\"),\n"
"        seen=ok.filter(g=>g.smp_sees).length, run=s.queue.jobs.find(j=>j.state===\"running\"), wait="
"s.queue.jobs.filter(j=>j.state===\"queued\").length;\n"
"  const card=(view,lab,big,note,cls=\"\")=>`<button class=\"stat\" data-go=\"${view}\"><span class=\""
"lab\">${lab}</span><span class=\"big ${cls}\">${big}</span><span class=\"note\">${note}</span></butt"
"on>`;\n"
"  const smpTxt={ok:[\"\342\234\223\",\"Connected \302\267 version \"+esc(sc.smp_version)],not_instal"
"led:[\"\342\234\227\",\"Not installed\"],api_disabled:[\"!\",\"API switched off\"],\n"
"    no_api:[\"!\",\"Not running, or older than 1.7\"],too_old:[\"\342\234\227\",\"Version \"+esc(sc."
"smp_version)+\" is too old\"],missing_features:[\"!\",\"Needs updating\"]}[st]||[\"\342\200\246\",\""
"Checking\"];\n"
"  $(\"#homeStats\").innerHTML=\n"
"    card(\"settings\",\"ShadowMount Plus\",smpTxt[0],smpTxt[1],st===\"ok\"\?\"st-ok\":st===\"not_ins"
"talled\"||st===\"too_old\"\?\"st-bad\":\"st-warn\")+\n"
"    card(\"attention\",\"Needs attention\",probs.length,probs.length\? `${probs.filter(g=>g.fix_dst)"
".length} with a one-tap fix` : \"Everything is in place\",probs.length\?\"st-warn\":\"st-ok\")+\n"
"    card(\"library\",\"Library\",ok.length,sc.smp_api\? `${seen} seen by ShadowMount` : \"games in t"
"he right place\")+\n"
"    card(\"queue\",\"Queue\",run\? Math.floor(run.bytes_total\? run.bytes_done/run.bytes_total*100:0"
")+\"%\" : wait,\n"
"      run\? esc(jobName(run))+(wait\?` \302\267 ${wait} waiting`:\"\") : wait\? \"jobs waiting\" : \""
"Nothing running\",run\?\"st-ok\":\"\");\n"
"  document.querySelectorAll(\"#homeStats [data-go]\").forEach(b=>b.onclick=()=>showView(b.dataset.go"
"));\n"
"}\n"
"function jobName(j){ const g=(state\?.scan.games||[]).find(x=>x.title_id===j.title_id && x.title); r"
"eturn g\? g.title : (j.title||j.title_id); }\n"
"\n"
"function renderDrives(s){\n"
"  $(\"#drives\").innerHTML = s.scan.drives.map(d=>{\n"
"    const used = d.total\? (1-d.avail/d.total)*100 : 0;\n"
"    return `<div class=\"drive\"><div class=\"title\">${esc(d.label)}</div><div class=\"path\">${esc"
"(d.mount)}</div>\n"
"      <div class=\"bar\"><i style=\"width:${used.toFixed(1)}%\"></i></div>\n"
"      <div class=\"stats\"><span><b>${fmtBytes(d.avail)}</b> free</span><span>of ${fmtBytes(d.total)"
"}</span></div></div>`;\n"
"  }).join(\"\") || '<div class=\"empty\">No drives found.</div>';\n"
"  const dest=$(\"#dest\"), cur=dest.value;\n"
"  dest.innerHTML = s.scan.drives.filter(d=>d.root).map(d=>`<option value=\"${esc(d.root)}\">\342\206"
"\222 ${esc(d.label)} (${esc(d.root)})</option>`).join(\"\");\n"
"  if(cur) dest.value=cur;\n"
"}\n"
"\n"
"function renderQueue(s){\n"
"  const jobs=s.queue.jobs; const active=jobs.filter(j=>j.state===\"queued\"||j.state===\"running\");"
"\n"
"  $(\"#qCount\").textContent=active.length;\n"
"  $(\"#pauseBtn\").textContent = s.queue.paused \? \"Resume\" : \"Pause\";\n"
"  if(!jobs.length){ $(\"#queue\").innerHTML='<div class=\"empty\">Nothing queued. Tick games in the "
"Library, or press Fix in Needs attention.</div>'; return; }\n"
"  const order={running:0,queued:1,failed:2,cancelled:3,done:4};\n"
"  const sorted=[...jobs].sort((a,b)=> order[a.state]-order[b.state] || (a.state===\"queued\"\?0:b.fi"
"nished_ms-a.finished_ms));\n"
"  $(\"#queue\").innerHTML = sorted.map(j=>{\n"
"    const verb = {fix:\"Fix\",move:\"Move\",copy:\"Copy\",extract:\"Extract\"}[j.type];\n"
"    let extra=\"\";\n"
"    if(j.state===\"running\"){\n"
"      const pct = j.bytes_total\? j.bytes_done/j.bytes_total*100 : 0;\n"
"      const prev=lastProg[j.id], now=Date.now();\n"
"      if(prev && now>prev.t){ const inst=(j.bytes_done-prev.b)/((now-prev.t)/1000); speeds[j.id]= sp"
"eeds[j.id]==null\? inst : speeds[j.id]*0.7+inst*0.3; }\n"
"      lastProg[j.id]={b:j.bytes_done,t:now};\n"
"      const sp=speeds[j.id]||0, eta= sp>0\? (j.bytes_total-j.bytes_done)/sp : 0;\n"
"      extra=`<div class=\"bar\"><i style=\"width:${pct.toFixed(1)}%\"></i></div>\n"
"        <div class=\"stats\"><span><b>${pct.toFixed(1)}%</b></span><span><b>${fmtBytes(j.bytes_done)"
"}</b> / ${fmtBytes(j.bytes_total)}</span>\n"
"        <span>files <b>${j.files_done}</b> / ${j.files_total}</span><span><b>${fmtBytes(sp)}/s</b></"
"span>\n"
"        ${eta\? `<span>about <b>${fmtTime(eta)}</b> left</span>`:\"\"}<span>${esc(j.phase)}</span></"
"div>\n"
"        <div class=\"row\" style=\"margin-top:6px\"><button class=\"small danger\" onclick=\"post('/"
"api/cancel\?id=${j.id}')\">Cancel</button></div>`;\n"
"    } else if(j.state===\"queued\"){\n"
"      extra=`<div class=\"row\" style=\"margin-top:6px\"><button class=\"small\" onclick=\"post('/ap"
"i/up\?id=${j.id}')\">\342\206\221 Earlier</button>\n"
"        <button class=\"small danger\" onclick=\"post('/api/cancel\?id=${j.id}')\">Remove</button>${"
"j.message\?`<span class=\"detail\">${esc(j.message)}</span>`:\"\"}</div>`;\n"
"    } else {\n"
"      const cls = j.state===\"done\"\?\"job-done\":\"job-fail\";\n"
"      const icon= j.state===\"done\"\?\"\342\234\223\":\"\342\234\227\";\n"
"      const nowSeen = j.state===\"done\" && (s.scan.games||[]).some(g=>g.path===j.dst && g.smp_sees)"
";\n"
"      const ver = nowSeen && !/sees it/.test(j.verify||\"\") \? '<div class=\"detail st-ok\">\342\234"
"\223 ShadowMount sees it now</div>'\n"
"                : j.verify\? `<div class=\"detail\">${/sees it/.test(j.verify)\?\"\342\234\223\":\"\342"
"\232\240\"} ${esc(j.verify)}</div>` : \"\";\n"
"      extra=`<div class=\"detail ${cls}\">${icon} ${esc(j.message)}</div>${ver}`;\n"
"    }\n"
"    return `<div class=\"card\"><div class=\"row\"><span class=\"badge\">${verb}</span><span class=\""
"title\">${esc(jobName(j))}</span>\n"
"      <span class=\"tid\">${esc(j.title_id)}</span><span class=\"spacer\"></span><span class=\"pill\""
">${j.state}</span></div>\n"
"      <div class=\"path\">${esc(j.src)}</div><div class=\"arrow\">\342\206\222 ${esc(j.dst)}</div>${"
"extra}</div>`;\n"
"  }).join(\"\");\n"
"}\n"
"\n"
"function renderProblems(s){\n"
"  const probs=s.scan.games.filter(g=>g.issue!==\"ok\");\n"
"  $(\"#pCount\").textContent=probs.length;\n"
"  $(\"#fixAllBtn\").disabled = !probs.some(g=>g.fix_dst);\n"
"  if(!probs.length){ $(\"#problems\").innerHTML = s.scan.running\? '<div class=\"empty\">Scanning\342"
"\200\246</div>' : '<div class=\"empty st-ok\">\342\234\223 Everything is where ShadowMount expects i"
"t.</div>'; return; }\n"
"  $(\"#problems\").innerHTML = probs.map(g=>`<div class=\"card\">\n"
"    <div class=\"row\"><span class=\"badge\">${esc(g.kind)}</span><span class=\"title\">${esc(gameNa"
"me(g))}</span><span class=\"tid\">${esc(g.title_id)}</span>\n"
"      <span class=\"spacer\"></span><span class=\"tid\">${gsize(g)}</span></div>\n"
"    <div class=\"path\">${esc(g.path)}</div>\n"
"    <div class=\"detail st-warn\">${esc(g.detail)}</div>\n"
"    ${g.fix_dst\? `<div class=\"arrow\">\342\206\222 ${esc(g.fix_dst)}</div>`:\"\"}\n"
"    <div class=\"row\" style=\"margin-top:6px\">\n"
"      ${g.fix_dst\? `<button class=\"small primary\" onclick=\"post('/api/job\?action=fix&id=${g.id}"
"')\">Fix (move here)</button>`:\"\"}\n"
"      ${s.scan.smp_api && (g.issue===\"too_deep\"||g.issue===\"outside_roots\"||g.issue===\"wrapped_"
"folder\")\? `<button class=\"small\" onclick=\"post('/api/manual\?id=${g.id}')\">Leave it, add to SM"
"P list</button>`:\"\"}\n"
"      ${g.kind===\"archive\"\? `<button class=\"small primary\" onclick=\"openArchive(${g.id})\">Ext"
"ract\342\200\246</button>`:\"\"}\n"
"      ${g.kind===\"pkg\"\? `<button class=\"small\" onclick=\"inspectPkg(${g.id})\">Check if convert"
"ible</button>`:\"\"}\n"
"    </div><div id=\"ax-${g.id}\"></div></div>`).join(\"\");\n"
"}\n"
"\n"
"const DRV_ORDER={\"/data\":0,\"/mnt/ext1\":1,\"/mnt/ext0\":2};\n"
"function driveAdvice(d,kind,need){\n"
"  const internal=d.mount===\"/data\", m2=d.mount===\"/mnt/ext1\", usb=d.mount.startsWith(\"/mnt/usb\""
")||d.mount===\"/mnt/ext0\";\n"
"  let rank=internal\?0:m2\?1:2, note;\n"
"  if(kind===\"folder\") note= internal\? \"Fastest for folder games: thousands of small files load q"
"uickest here.\"\n"
"                       : m2\? \"Very good: fast NVMe, slightly behind internal for small-file loadin"
"g.\"\n"
"                       : \"Works, but slowest: small-file reads over USB mean longer loads and slow "
"moves.\";\n"
"  else if(kind===\"pfs\"||kind===\"pfsc\") note= internal\? \"Best: PFS images are experimental in S"
"hadowMount; internal is the safest place.\"\n"
"                       : \"Works, but PFS images are experimental; internal is safer.\";\n"
"  else note= internal\? \"Best: ShadowMount's optimised image mode only applies to images on the int"
"ernal drive.\"\n"
"             : m2\? \"Good: standard image mode. One big file, so it copies at full speed.\"\n"
"             : \"OK: one big file is fine over USB, though loading is slower than NVMe.\";\n"
"  const fits=d.avail>=need;\n"
"  return {rank:fits\?rank:9,fits,note};\n"
"}\n"
"const PKG_VERDICT={\n"
"  convertible:[\"st-ok\",\"Convertible: the game data isn't compressed. The converter isn't built ye"
"t, but this one will work.\"],\n"
"  convertible_zlib:[\"st-ok\",\"Convertible: zlib-compressed game data. The converter isn't built ye"
"t, but this one will work.\"],\n"
"  needs_kraken:[\"st-warn\",\"Kraken-compressed game data. Converting needs a Kraken decoder on the "
"console, which is the next thing to build.\"],\n"
"  unknown_inner:[\"st-warn\",\"Unlocked, but the game data is in a layout Game Library Manager doesn"
"'t recognise yet.\"],\n"
"  locked:[\"st-bad\",\"Not convertible: it isn't locked with the standard fake-package passcode. Ins"
"tall it, or get the game as a folder, exFAT image or 7z instead.\"],\n"
"  retail:[\"st-bad\",\"Retail-signed package: it can only be installed, not converted.\"],\n"
"  unknown:[\"st-bad\",\"Couldn't read this package.\"]};\n"
"async function inspectPkg(id){\n"
"  const box=$(\"#ax-\"+id); box.innerHTML='<div class=\"detail\">Reading the package header\342\200\246"
"</div>';\n"
"  let a; try{ a=await fetch(\"/api/pkginfo\?id=\"+id).then(r=>r.json()); }catch(e){ box.innerHTML='<"
"div class=\"detail st-bad\">Couldn\\'t read the package.</div>'; return; }\n"
"  const v=PKG_VERDICT[a.verdict]||PKG_VERDICT.unknown;\n"
"  let h=`<div class=\"card\" style=\"background:var(--bg)\"><div class=\"detail ${v[0]}\"><b>${esc(v"
"[1])}</b></div>`;\n"
"  if(a.summary) h+=`<div class=\"explain\">${esc(a.summary)}</div>`;\n"
"  if(a.error) h+=`<div class=\"explain\">${esc(a.error)}</div>`;\n"
"  if(a.content_id) h+=`<div class=\"explain\">Content ID <code>${esc(a.content_id)}</code>${a.outer&"
"&a.outer.key&&a.outer.key!==\"none\"\?` \302\267 key ${esc(a.outer.key)}`:\"\"}${a.inner&&a.inner.na"
"ps_files>0\?` \302\267 ${a.inner.naps_files} files inside`:\"\"}${a.inner&&a.inner.logical\?` \302\267"
" ${fmtBytes(a.inner.logical)} unpacked`:\"\"}</div>`;\n"
"  box.innerHTML=h+\"</div>\";\n"
"}\n"
"async function openArchive(id){\n"
"  const box=$(\"#ax-\"+id); box.innerHTML='<div class=\"detail\">Reading archive\342\200\246</div>';"
"\n"
"  let a; try{ a=await fetch(\"/api/archive\?id=\"+id).then(r=>r.json()); }catch(e){ box.innerHTML='<"
"div class=\"detail st-bad\">Couldn\\'t read the archive.</div>'; return; }\n"
"  if(!a.ok){ box.innerHTML=`<div class=\"detail st-bad\">${esc(a.message)}</div>`; return; }\n"
"  if(!a.candidates.length){ box.innerHTML=`<div class=\"detail st-warn\">No game found inside (no sc"
"e_sys/param.json + eboot.bin, and no .exfat/.ffpkg/.ffpfs image). ${a.files} files, ${fmtBytes(a.unp"
"acked)}.</div>`; return; }\n"
"  const speed = !a.supported\? `<span class=\"st-bad\">Uses ${esc(a.methods)} \342\200\223 not suppo"
"rted here; extract it on a PC.</span>`\n"
"    : /store/.test(a.methods)&&!/LZMA/.test(a.methods)\? \"Stored without compression: extraction ru"
"ns at disk speed.\"\n"
"    : a.multithread\? \"LZMA2: decoded on several CPU cores when the archive was made with multi-thr"
"eaded 7-Zip.\"\n"
"    : \"LZMA: single-core decoding, so this one is slower.\";\n"
"  let h=`<div class=\"card\" style=\"background:var(--bg)\"><div class=\"detail\"><b>${a.volumes>1\?"
"a.volumes+\" volumes, \":\"\"}${fmtBytes(a.archive_size)}</b> archive \302\267 ${a.files} files \302"
"\267 ${fmtBytes(a.unpacked)} unpacked \302\267 ${esc(a.methods)}</div><div class=\"explain\">${speed"
"}</div>`;\n"
"  const exSize=(a.extras||[]).reduce((n,e)=>n+e.size,0);\n"
"  const sibSize=(a.siblings||[]).reduce((n,e)=>n+e.size,0);\n"
"  a.candidates.forEach((c,ci)=>{\n"
"    const need=(c.size+exSize+sibSize)*1.02+256*2**20;\n"
"    const drives=state.scan.drives.filter(d=>d.root).map(d=>({d,...driveAdvice(d,c.kind,need)})).sor"
"t((x,y)=>x.rank-y.rank);\n"
"    const best=drives.find(x=>x.fits);\n"
"    h+=`<div class=\"detail\" style=\"margin-top:8px\"><b>Found:</b> ${c.kind===\"folder\"\?\"folder"
" game\":esc(c.kind)+\" image\"} <code>${esc(c.inner||\"(archive root)\")}</code> \302\267 ${c.files}"
" files \302\267 ${fmtBytes(c.size)}<br>\n"
"      Extracts to <code>&lt;drive&gt;/homebrew/${esc(c.name)}</code>${c.kind===\"folder\"&&c.inner\?"
"\" (the wrapper folders are dropped, so ShadowMount sees it straight away)\":\"\"}.</div>`;\n"
"    h+=drives.map((x,i)=>`<label class=\"lib-item\" style=\"padding:6px 0\"><input type=\"radio\" na"
"me=\"axd-${id}-${ci}\" value=\"${esc(x.d.root)}\" ${x===best\?\"checked\":\"\"} ${x.fits\?\"\":\"dis"
"abled\"}>\n"
"      <div class=\"grow\"><div class=\"row\"><span class=\"title\">${esc(x.d.label)}</span>${x===bes"
"t\?'<span class=\"badge\" style=\"color:var(--ok);border-color:#23472c\">recommended</span>':\"\"}\n"
"      <span class=\"tid\">${fmtBytes(x.d.avail)} free</span></div><div class=\"explain\" style=\"mar"
"gin:0\">${x.fits\?esc(x.note):'<span class=\"st-bad\">Not enough free space</span>'}</div></div></la"
"bel>`).join(\"\");\n"
"    if((a.extras||[]).length){\n"
"      h+=`<label class=\"row\" style=\"margin:6px 0;flex-wrap:nowrap;align-items:flex-start\"><input"
" type=\"checkbox\" id=\"axex-${id}-${ci}\" checked>\n"
"        <span class=\"detail\">Also extract everything else (${fmtBytes(exSize)}) to <code>&lt;drive"
"&gt;/game-extras/${esc(c.name)}</code>:\n"
"        <span style=\"color:var(--dim)\">${a.extras.map(e=>esc(e.path)+\" (\"+fmtBytes(e.size)+\")\""
").join(\", \")}</span><br>\n"
"        <span style=\"color:var(--dim)\">Fixes, backports and DLC are kept with their original folde"
"r names, outside ShadowMount's scan folders.</span></span></label>`;\n"
"    }\n"
"    if((a.siblings||[]).length){\n"
"      h+=`<label class=\"row\" style=\"margin:6px 0;flex-wrap:nowrap;align-items:flex-start\"><input"
" type=\"checkbox\" id=\"axsib-${id}-${ci}\" checked>\n"
"        <span class=\"detail\">Also copy the other items next to the archive (${fmtBytes(sibSize)}) "
"to <code>&lt;drive&gt;/game-extras/${esc(c.name)}</code>:\n"
"        <span style=\"color:var(--dim)\">${a.siblings.map(e=>esc(e.path)+\" (\"+fmtBytes(e.size)+\")"
"\").join(\", \")}</span></span></label>`;\n"
"    }\n"
"    h+=`<label class=\"row\" style=\"margin:6px 0;flex-wrap:nowrap\"><input type=\"checkbox\" id=\"a"
"xdel-${id}-${ci}\"> <span class=\"detail\">Delete the archive afterwards (only if every file passes "
"its CRC check)</span></label>\n"
"      <button class=\"small primary\" ${best&&a.supported\?\"\":\"disabled\"} onclick=\"startExtract"
"(${id},${ci})\">Extract to selected drive</button>`;\n"
"  });\n"
"  box.innerHTML=h+\"</div>\"; box._a=a;\n"
"}\n"
"async function startExtract(id,ci){\n"
"  const a=$(\"#ax-\"+id)._a, c=a.candidates[ci];\n"
"  const r=document.querySelector(`input[name=\"axd-${id}-${ci}\"]:checked`); if(!r){ toast(\"Pick a "
"drive\"); return; }\n"
"  const del=$(`#axdel-${id}-${ci}`).checked\?1:0;\n"
"  const exb=$(`#axex-${id}-${ci}`); const ex=exb\? (exb.checked\?1:0) : 0;\n"
"  const sb=$(`#axsib-${id}-${ci}`); const sib=sb\? (sb.checked\?1:0) : 0;\n"
"  const ok=await post(`/api/extract\?id=${id}&inner=${encodeURIComponent(c.inner)}&name=${encodeURIC"
"omponent(c.name)}&root=${encodeURIComponent(r.value)}&delete=${del}&extras=${ex}&siblings=${sib}`);\n"
"  if(ok) $(\"#ax-\"+id).innerHTML='<div class=\"detail st-ok\">Queued. You can follow it in the Queu"
"e.</div>';\n"
"}\n"
"\n"
"function renderLibrary(s){\n"
"  const games=s.scan.games; $(\"#lCount\").textContent=games.length;\n"
"  if(!games.length){ $(\"#library\").innerHTML='<div class=\"empty\">'+(s.scan.running\?\"Scanning\342"
"\200\246\":\"No games found.\")+'</div>'; return; }\n"
"  const byDrive={};\n"
"  games.forEach(g=>(byDrive[g.drive]=byDrive[g.drive]||[]).push(g));\n"
"  $(\"#library\").innerHTML = Object.keys(byDrive).map(d=>{\n"
"    const list=byDrive[d].sort((a,b)=>gameName(a).localeCompare(gameName(b)));\n"
"    const total=list.reduce((n,g)=>n+g.size,0);\n"
"    return `<div class=\"drive-head\">${esc(driveLabel(d))} \302\267 ${list.length} item${list.lengt"
"h===1\?\"\":\"s\"}, ${fmtBytes(total)}</div><div class=\"libcard\">`+\n"
"      list.map(g=>{\n"
"        let st;\n"
"        if(g.issue!==\"ok\") st=`<span class=\"st-bad\">\342\234\227 ${esc(g.issue.replace(/_/g,\" \""
"))}</span>`;\n"
"        else if(!s.scan.smp_api) st=`<span class=\"st-ok\">\342\234\223 in the right place</span>`;\n"
"        else if(g.smp_sees) st=`<span class=\"st-ok\">\342\234\223 ShadowMount sees it${g.mounted\?\""
" (mounted)\":\"\"}</span>`;\n"
"        else st=`<span class=\"st-warn\">\342\232\240 In the right place, but ShadowMount hasn't reg"
"istered it yet</span>`;\n"
"        return `<label class=\"lib-item\"><input type=\"checkbox\" data-id=\"${g.id}\" ${sel.has(g.i"
"d)\?\"checked\":\"\"}>\n"
"          <div class=\"grow\"><div class=\"row\"><span class=\"title\">${esc(gameName(g))}</span><sp"
"an class=\"tid\">${esc(g.title_id)}</span>\n"
"          <span class=\"badge\">${esc(g.kind)}</span></div>\n"
"          <div class=\"path\">${esc(g.path)}</div>\n"
"          <div class=\"stats\"><span>${gsize(g)}</span>${g.kind===\"folder\"&&g.size_state\?`<span>$"
"{g.files} files</span>`:\"\"}<span>${st}</span>\n"
"          ${g.savefix===1\?'<span class=\"st-warn\">save fix available</span>':g.savefix===2\?'<span"
" class=\"st-ok\">save fix on</span>':g.has_fakelib\?'<span>has fakelib</span>':\"\"}</div></div></la"
"bel>`;\n"
"      }).join(\"\")+\"</div>\";\n"
"  }).join(\"\");\n"
"  document.querySelectorAll(\"#library input[type=checkbox]\").forEach(cb=>cb.onchange=()=>{\n"
"    const id=+cb.dataset.id; cb.checked\? sel.add(id) : sel.delete(id); renderBatch();\n"
"  });\n"
"}\n"
"\n"
"function renderFakelib(s){\n"
"  const withFl=s.scan.games.filter(g=>g.has_fakelib);\n"
"  const need=withFl.filter(g=>g.savefix===1).length;\n"
"  $(\"#sfCount\").textContent=need;\n"
"  $(\"#sfAllBtn\").disabled=!need;\n"
"  $(\"#sfAllBtn\").textContent= need\? `Apply to all (${need})` : \"Apply to all\";\n"
"  let h=`<div class=\"explain\">Some backports ship their own copy of the PS5 save library (<code>li"
"bSceSaveData.sprx</code>) in the game's <code>fakelib</code> folder,\n"
"    which can stop saving from working. The <b>save fix</b> switches that one file off by renaming i"
"t to <code>.disabled</code>, so the\n"
"    console's own save library is used instead. Nothing is deleted, <b>Undo</b> puts it back, and it"
" takes effect the next time the game starts.\n"
"    If a game then fails to boot, undo it for that game.</div>`;\n"
"  const gs=s.global_savefix \?\? s.scan.global_savefix;\n"
"  if(gs){\n"
"    h+=`<div class=\"card\"><div class=\"title\">Global fakelib <span class=\"tid\">/data/shadowmoun"
"t/fakelib</span></div>\n"
"      <div class=\"detail st-warn\">Applies to <b>every</b> game. ${gs===1\?\"Contains a save librar"
"y.\":\"Save fix is on.\"}</div>\n"
"      <button class=\"small ${gs===1\?\"primary\":\"\"}\" onclick=\"post('/api/savefix\?id=global${g"
"s===2\?\"&undo=1\":\"\"}')\">${gs===1\?\"Apply save fix (all games)\":\"Undo\"}</button></div>`;\n"
"  }\n"
"  if(!withFl.length) h+='<div class=\"empty\">No games have a fakelib folder, so there is nothing to"
" fix.</div>';\n"
"  h+=withFl.sort((a,b)=>b.savefix-a.savefix).map(g=>{\n"
"    const files=g.fakelib\? g.fakelib.split(\", \").filter(Boolean):[];\n"
"    const state= g.savefix===1\? `<span class=\"fixstate st-warn\">\342\232\240 Save library active "
"\342\200\224 save fix available</span>`\n"
"               : g.savefix===2\? `<span class=\"fixstate st-ok\">\342\234\223 Save fix on</span>`\n"
"               : `<span class=\"fixstate\" style=\"color:var(--dim)\">No save library in this fakeli"
"b \342\200\224 save fix not needed</span>`;\n"
"    const btn= g.savefix===1\? `<button class=\"small primary\" onclick=\"post('/api/savefix\?id=${g"
".id}')\">Apply save fix</button>`\n"
"             : g.savefix===2\? `<button class=\"small\" onclick=\"post('/api/savefix\?id=${g.id}&und"
"o=1')\">Undo save fix</button>` : \"\";\n"
"    return `<div class=\"card\"><div class=\"row\"><span class=\"title\">${esc(gameName(g))}</span><"
"span class=\"tid\">${esc(g.title_id)}</span></div>\n"
"      <div class=\"row\" style=\"margin:4px 0\">${state}<span class=\"spacer\"></span>${btn}</div>\n"
"      <details><summary>Advanced: individual fakelib files (${files.length})</summary>\n"
"      <div class=\"explain\">Tap a file to switch it off (rename to .disabled) or back on. Only chan"
"ge these if you know what they do.</div>\n"
"      <div class=\"row\">${files.map(f=>{\n"
"        const off=/\\.disabled$/i.test(f);\n"
"        return `<button class=\"small flbtn\" data-id=\"${g.id}\" data-file=\"${esc(f)}\">${off\?\"\342"
"\206\272 \":\"\342\250\257 \"}${esc(f)}</button>`;\n"
"      }).join(\"\")}</div></details></div>`;\n"
"  }).join(\"\");\n"
"  $(\"#fakelib\").innerHTML=h;\n"
"  document.querySelectorAll(\"#fakelib .flbtn\").forEach(b=>b.onclick=()=>\n"
"    post(`/api/fakelib\?id=${b.dataset.id}&file=${encodeURIComponent(b.dataset.file)}`));\n"
"}\n"
"\n"
"function renderPush(s){\n"
"  const on=s.push.ntfy||s.push.webhook;\n"
"  $(\"#push\").innerHTML = `<div class=\"detail\">PS5 pop-ups: <span class=\"st-ok\">on</span> \302\267"
" Phone push:\n"
"    ${on\? `<span class=\"st-ok\">${[s.push.ntfy&&\"ntfy\",s.push.webhook&&\"webhook\"].filter(Boole"
"an).join(\" + \")}</span>`:'<span class=\"st-warn\">not set up</span>'}</div>\n"
"    ${on\? `<button class=\"small\" onclick=\"post('/api/testpush')\">Send test push</button>`:\n"
"    `<div class=\"detail\" style=\"color:var(--dim)\">Install the free <b>ntfy</b> app, subscribe to"
" a hard-to-guess topic, then add\n"
"     <code>ntfy_url=https://ntfy.sh/your-topic</code> to <code>/data/game-library-manager/config.ini"
"</code> and reload the payload.</div>`}`;\n"
"}\n"
"\n"
"function renderTile(s){\n"
"  const t=s.tile||{}; const st=t.state;\n"
"  const look={installed:[\"st-ok\",\"\342\234\223 On your home screen\"],waiting_smp:[\"st-warn\",\""
"\342\232\240 Waiting for ShadowMount\"],\n"
"    error:[\"st-bad\",\"\342\234\227 Couldn't install\"],disabled:[\"\",\"Switched off\"],skipped:[\""
"st-ok\",\"\342\234\223 Started from the tile\"],unknown:[\"\",\"Checking\342\200\246\"]}[st]||[\"\","
"st];\n"
"  $(\"#tile\").innerHTML=`<div class=\"detail\"><span class=\"fixstate ${look[0]}\">${look[1]}</span"
"> <span class=\"tid\">${esc(t.title_id||\"\")}</span></div>\n"
"    <div class=\"explain\">${esc(t.message||\"\")}</div>\n"
"    <div class=\"explain\">The <b>Game Library Manager</b> tile opens this page in the PS5 browser, "
"like the Payload Manager and Web File Manager tiles.\n"
"    It never starts the app itself: your payload loader does that, after ShadowMount. If the app isn"
"'t running, the browser just can't connect.\n"
"    The tile is a web link installed as <code>${esc(t.path||\"/user/app/GLMG00001\")}</code>.</div>\n"
"    <button class=\"small\" onclick=\"post('/api/tile')\">${st===\"installed\"\?\"Reinstall tile\":\""
"Install tile now\"}</button>`;\n"
"}\n"
"\n"
"function renderBatch(){\n"
"  $(\"#batch\").style.display = sel.size && curView===\"library\"\? \"block\":\"none\";\n"
"  $(\"#selCount\").textContent = sel.size+\" selected\";\n"
"}\n"
"\n"
"async function queueSelected(action){\n"
"  const root=$(\"#dest\").value; if(!root){ toast(\"Pick a destination\"); return; }\n"
"  let ok=0, msgs=[];\n"
"  for(const id of sel){\n"
"    const r=await fetch(`/api/job\?action=${action}&id=${id}&root=${encodeURIComponent(root)}`,{meth"
"od:\"POST\"}).then(r=>r.json()).catch(()=>({ok:false,message:\"network\"}));\n"
"    if(r.ok) ok++; else msgs.push(r.message);\n"
"  }\n"
"  sel.clear(); renderBatch();\n"
"  toast(`${ok} queued`+(msgs.length\? \" \302\267 \"+msgs[0]:\"\"));\n"
"  refresh();\n"
"}\n"
"\n"
"async function refresh(){\n"
"  try{\n"
"    const s = await fetch(\"/api/state\",{cache:\"no-store\"}).then(r=>r.json());\n"
"    state=s;\n"
"    renderHeader(s); renderDrives(s); renderQueue(s); renderTile(s);\n"
"    const sig = s.scan.finished_ms+\":\"+s.scan.running+\":\"+s.scan.games.map(g=>g.size_state).join"
"(\"\");\n"
"    if(sig!==refresh.sig){ refresh.sig=sig; renderProblems(s); renderLibrary(s); renderFakelib(s); r"
"enderPush(s); }\n"
"    guideLive();\n"
"    if(!guideAuto){ guideAuto=true; if(!s.guide_done) guideShow(0); }\n"
"  }catch(e){ $(\"#smpPill\").className=\"pill bad\"; $(\"#smpPill\").textContent=\"PS5 not respondin"
"g\"; }\n"
"}\n"
"\n"
"/* ---------- views ---------- */\n"
"let curView=\"home\";\n"
"function showView(v){\n"
"  curView=v;\n"
"  document.querySelectorAll(\".view\").forEach(e=>e.hidden=e.dataset.view!==v);\n"
"  document.querySelectorAll(\".nav-item\").forEach(b=>b.classList.toggle(\"on\",b.dataset.view===v))"
";\n"
"  window.scrollTo(0,0); renderBatch();\n"
"  try{ sessionStorage.setItem(\"glmView\",v); }catch(e){}\n"
"}\n"
"document.querySelectorAll(\".nav-item\").forEach(b=>b.onclick=()=>showView(b.dataset.view));\n"
"try{ const v=sessionStorage.getItem(\"glmView\"); showView(v&&document.querySelector(`.view[data-vie"
"w=\"${v}\"]`)\?v:\"home\"); }catch(e){ showView(\"home\"); }\n"
"\n"
"/* ---------- first-use guide ---------- */\n"
"const SMP_HELP={\n"
"  ok:s=>`<span class=\"st-ok\">\342\234\223 ShadowMount Plus ${esc(s.scan.smp_version)} is running.<"
"/span> Every move will be checked against it, so you know the game shows up.`,\n"
"  not_installed:()=>`<span class=\"st-bad\">\342\234\227 ShadowMount Plus isn't installed</span> (no"
" <code>/data/shadowmount</code> folder). Install and load it, then press Rescan. Finding and moving "
"games still works without it.`,\n"
"  api_disabled:()=>`<span class=\"st-warn\">\342\232\240 ShadowMount's API is switched off.</span> S"
"et <code>api_enabled=1</code> in <code>/data/shadowmount/config.ini</code> so moved games can be che"
"cked.`,\n"
"  no_api:()=>`<span class=\"st-warn\">\342\232\240 ShadowMount isn't answering.</span> It's either n"
"ot loaded yet or older than 1.7. Load ShadowMount Plus 1.7 or newer, then press Rescan.`,\n"
"  too_old:s=>`<span class=\"st-bad\">\342\234\227 ShadowMount ${esc(s.scan.smp_version)} is too old."
"</span> Update to ShadowMount Plus 1.7 or newer.`,\n"
"  missing_features:()=>`<span class=\"st-warn\">\342\232\240 This ShadowMount 1.7 build is missing a"
" feature the checks use.</span> Update to the latest ShadowMount Plus.`};\n"
"function phoneUrl(s){ return s.ip\? `http://${s.ip}:${s.port}` : location.origin; }\n"
"const GUIDE=[\n"
" {t:\"Welcome to Game Library Manager\", view:\"home\",\n"
"  b:`<p>It finds games that ShadowMount Plus can't see, puts them where ShadowMount looks, and moves"
", copies or extracts games for you in a queue.</p>\n"
"     <p>Everything runs on the PS5. This page, on the PS5 or your phone, is just a window onto it, s"
"o you can close it any time without stopping anything.</p>\n"
"     <p>This guide takes about 2 minutes. <b>Nothing on your drives changes until you press a button"
".</b></p>`},\n"
" {t:\"Is ShadowMount running\?\", view:\"home\", target:\"#homeStats .stat\",\n"
"  b:`<p>The first card on the Overview shows whether ShadowMount Plus is connected. Load order matte"
"rs: ShadowMount Plus first, then Game Library Manager. Your payload loader's autoload list can do th"
"is for you every boot.</p>`,\n"
"  live:s=>SMP_HELP[s.scan.smp_status]\?.(s)||\"Checking\342\200\246\"},\n"
" {t:\"Scan your drives\", view:\"home\", target:\"#homeStats\", enter:\"scan\",\n"
"  b:`<p>The app is now looking through the internal SSD, M.2 drive and any USB drives for games, 7z "
"archives and .pkg files. It only reads; nothing is moved.</p>`,\n"
"  live:s=>{ const sc=s.scan;\n"
"    if(sc.running) return `<b>Scanning\342\200\246</b> ${sc.dirs_seen} folders checked, ${sc.found} "
"found so far<div class=\"path\">${esc(sc.current)}</div>`;\n"
"    const probs=sc.games.filter(g=>g.issue&&g.issue!==\"ok\").length;\n"
"    return `<span class=\"st-ok\">\342\234\223 Scan finished.</span> ${sc.games.length} item(s) on $"
"{sc.drives.length} drive(s). ${probs\? `<b>${probs}</b> need attention.`:\"Nothing needs attention.\""
"}${sc.sizing\?\" Game sizes are still being measured in the background.\":\"\"}`; }},\n"
" {t:\"Drives\", view:\"home\", target:\"#driveSec\",\n"
"  b:`<p>Every drive the app found, with its free space. Moves and extractions only offer drives with"
" enough room.</p><p>Missing a drive\? Plug it in, then press <b>Rescan drives</b> on the Overview.</"
"p>`,\n"
"  live:s=>s.scan.drives.map(d=>`${esc(d.label)} <span class=\"tid\">${esc(d.mount)}</span>: <b>${fmt"
"Bytes(d.avail)}</b> free`).join(\"<br>\")||\"No drives found yet.\"},\n"
" {t:\"Needs attention\", view:\"attention\", target:\"#problems\",\n"
"  b:`<p>Games ShadowMount won't pick up, with the reason and where they should go. The buttons you'l"
"l see:</p>\n"
"     <ul><li><b>Fix (move here)</b>: moves it to the right spot. On the same drive this is instant.<"
"/li>\n"
"     <li><b>Fix all</b>: queues every suggested fix in one go.</li>\n"
"     <li><b>Extract\342\200\246</b>: unpacks a 7z onto a drive you choose, with fixes, backports and"
" DLC kept beside it.</li>\n"
"     <li><b>Check if convertible</b>: reads a .pkg's header and tells you whether it can ever be con"
"verted.</li></ul>`,\n"
"  live:s=>{ const p=s.scan.games.filter(g=>g.issue&&g.issue!==\"ok\"), f=p.filter(g=>g.fix_dst).leng"
"th;\n"
"    return p.length\? `<b>${p.length}</b> item(s) here, <b>${f}</b> with a one-tap fix.` : `<span cl"
"ass=\"st-ok\">\342\234\223 Nothing needs attention right now.</span>`; }},\n"
" {t:\"Library\", view:\"library\", target:\"#library\",\n"
"  b:`<p>Every game on every drive, grouped by drive, with whether ShadowMount sees it.</p>\n"
"     <p>To move games: tick them, pick a drive in the bar at the bottom, then press <b>Move</b>. <b>"
"Copy</b> keeps the original, so you'd have two copies.</p>`,\n"
"  live:s=>`<b>${s.scan.games.filter(g=>g.kind!==\"archive\"&&g.kind!==\"pkg\").length}</b> game(s) i"
"n your library.`},\n"
" {t:\"Queue\", view:\"queue\", target:\"#queue\",\n"
"  b:`<p>Moves, fixes and extractions run here one at a time, in the background, with speed and time "
"left. You get a PS5 pop-up as each one finishes.</p>\n"
"     <ul><li><b>Pause</b> holds the queue after the current job.</li>\n"
"     <li><b>Stop batch</b> stops the current job (its half-copy is deleted, the original stays) and "
"cancels the rest. Games that already finished are never undone.</li></ul>`,\n"
"  live:s=>{ const a=s.queue.jobs.filter(j=>j.state===\"queued\"||j.state===\"running\").length; retu"
"rn a\? `<b>${a}</b> job(s) waiting or running.` : \"The queue is empty.\"; }},\n"
" {t:\"Save fix\", view:\"savefix\", target:\"#fakelib\",\n"
"  b:`<p>For backported games that won't save. The fix switches off the game's own copy of the save l"
"ibrary so the console's is used instead.</p>\n"
"     <p>Nothing is deleted, <b>Undo</b> reverses it, and it takes effect the next time the game star"
"ts.</p>`,\n"
"  live:s=>{ const n=s.scan.games.filter(g=>g.savefix===1).length, on=s.scan.games.filter(g=>g.savefi"
"x===2).length;\n"
"    return n\? `<span class=\"st-warn\"><b>${n}</b> game(s) could use the save fix.</span>${on\?` ${"
"on} already have it on.`:\"\"}` : on\? `<span class=\"st-ok\">\342\234\223 ${on} game(s) have the sa"
"ve fix on.</span>` : \"No games need it.\"; }},\n"
" {t:\"ShadowMount scan depth\", view:\"settings\", target:\"#depthLbl\",\n"
"  b:`<p>This sets how deep ShadowMount looks for games, and writes it to ShadowMount's own settings."
"</p>\n"
"     <ul><li><b>1</b>: only games directly inside <code>homebrew</code>.</li>\n"
"     <li><b>2</b>: also one folder deeper, e.g. <code>homebrew/PS5/&lt;game&gt;</code>.</li></ul>\n"
"     <p>Needs attention always follows this setting.</p>`,\n"
"  live:s=>`Currently <b>${s.scan.depth}</b>.`},\n"
" {t:\"Home tile and your phone\", view:\"settings\", target:\"#tileSec\",\n"
"  b:`<p>The <b>Game Library Manager</b> tile on your home screen opens this page in the PS5 browser."
" It never starts the app itself.</p>\n"
"     <p>To use your phone instead, open the address below in its browser while it's on the same Wi-F"
"i. Both always show the same thing.</p>`,\n"
"  live:s=>`Phone address: <b>${esc(phoneUrl(s))}</b><br>Tile: ${esc((s.tile&&s.tile.message)||\"chec"
"king\342\200\246\")}`},\n"
" {t:\"Phone notifications (optional)\", view:\"settings\", target:\"#pushSec\",\n"
"  b:`<p>For long batches you can get a push on your phone each time a job finishes, using the free <"
"b>ntfy</b> app or a Home Assistant webhook. This section shows how to set it up.</p>`,\n"
"  live:s=>(s.push.ntfy||s.push.webhook)\? `<span class=\"st-ok\">\342\234\223 Phone push is set up.<"
"/span>` : \"Not set up. PS5 pop-ups still work.\"},\n"
" {t:\"You're set\", view:\"attention\", target:\"#problems\",\n"
"  b:`<p>A good place to start is <b>Needs attention</b>, shown here.</p>\n"
"     <p>Use the menu to move between sections. You can reopen this guide any time with <b>Show the g"
"uide</b> at the bottom of the menu.</p>`}\n"
"];\n"
"let gi=-1, guideAuto=false;\n"
"function guideShow(i){\n"
"  gi=Math.max(0,Math.min(GUIDE.length-1,i)); const st=GUIDE[gi];\n"
"  document.body.classList.add(\"guiding\"); $(\"#guide\").style.display=\"block\";\n"
"  document.querySelectorAll(\".guide-hi\").forEach(e=>e.classList.remove(\"guide-hi\"));\n"
"  $(\"#gStep\").textContent=`Step ${gi+1} of ${GUIDE.length}`;\n"
"  $(\"#gTitle\").textContent=st.t; $(\"#gBody\").innerHTML=st.b;\n"
"  $(\"#gDots\").innerHTML=GUIDE.map((_,k)=>`<i class=\"${k<=gi\?\"on\":\"\"}\"></i>`).join(\"\");\n"
"  $(\"#gBack\").disabled=gi===0;\n"
"  $(\"#gNext\").textContent= gi===GUIDE.length-1\? \"Finish\" : \"Next\";\n"
"  $(\"#gSkip\").style.visibility= gi===GUIDE.length-1\? \"hidden\":\"visible\";\n"
"  if(st.view && st.view!==curView) showView(st.view);\n"
"  if(st.target){ const el=$(st.target); if(el){ el.classList.add(\"guide-hi\");\n"
"    const top=el.getBoundingClientRect().top+window.scrollY-24; window.scrollTo({top:Math.max(0,top-"
"140),behavior:\"smooth\"}); } }\n"
"  if(st.enter===\"scan\" && state && !state.scan.running && !GUIDE.scanned){ GUIDE.scanned=true; fet"
"ch(\"/api/scan\",{method:\"POST\"}).then(()=>refresh()).catch(()=>{}); }\n"
"  guideLive(); $(\"#gNext\").focus();\n"
"}\n"
"function guideLive(){ if(gi<0||!state) return; const f=GUIDE[gi].live; $(\"#gLive\").innerHTML= f\? "
"f(state) : \"\"; }\n"
"function guideClose(done){\n"
"  gi=-1; $(\"#guide\").style.display=\"none\"; document.body.classList.remove(\"guiding\");\n"
"  document.querySelectorAll(\".guide-hi\").forEach(e=>e.classList.remove(\"guide-hi\"));\n"
"  if(done) fetch(\"/api/guide\?done=1\",{method:\"POST\"}).catch(()=>{});\n"
"}\n"
"$(\"#gNext\").onclick=()=>{ if(gi===GUIDE.length-1) guideClose(true); else guideShow(gi+1); };\n"
"$(\"#gBack\").onclick=()=>guideShow(gi-1);\n"
"$(\"#gSkip\").onclick=()=>guideClose(true);\n"
"$(\"#guideBtn\").onclick=$(\"#guideBtn2\").onclick=()=>{ GUIDE.scanned=false; guideShow(0); };\n"
"\n"
"$(\"#scanBtn\").onclick=()=>post(\"/api/scan\");\n"
"$(\"#depthSel\").onchange=e=>{\n"
"  const d=e.target.value;\n"
"  if(confirm(`Set ShadowMount's scan depth to ${d}\?\\n\\n${d===\"2\"\?\"ShadowMount will also look "
"one folder deeper, e.g. homebrew/PS5/<game>. Games already in place are not affected.\":\"ShadowMoun"
"t will only look directly inside each homebrew folder. Games kept one folder deeper will disappear f"
"rom the home screen until moved.\"}\\n\\nThis edits /data/shadowmount/config.ini (other settings are"
" kept).`))\n"
"    post(\"/api/depth\?depth=\"+d); else e.target.value=String(state.scan.depth);\n"
"};\n"
"$(\"#fixAllBtn\").onclick=()=>{ if(confirm(\"Queue every suggested fix\?\")) post(\"/api/fixall\"); "
"};\n"
"$(\"#pauseBtn\").onclick=()=>post(state\?.queue.paused\? \"/api/resume\":\"/api/pause\");\n"
"$(\"#clearBtn\").onclick=()=>post(\"/api/clear\");\n"
"$(\"#stopBtn\").onclick=()=>{\n"
"  const jobs=state\?.queue.jobs||[], run=jobs.filter(j=>j.state===\"running\").length, wait=jobs.fil"
"ter(j=>j.state===\"queued\").length,\n"
"        done=jobs.filter(j=>j.state===\"done\").length;\n"
"  if(!run&&!wait){ toast(\"Nothing to stop\"); return; }\n"
"  if(confirm(`Stop the batch\?\\n\\n\342\200\242 ${run\?\"The game copying now is stopped and its pa"
"rtial copy deleted (the original stays put).\":\"Nothing is running right now.\"}\\n\342\200\242 ${w"
"ait} waiting job(s) are cancelled.\\n\342\200\242 ${done} finished game(s) stay exactly where they a"
"re \342\200\224 nothing is undone.`))\n"
"    post(\"/api/cancelall\");\n"
"};\n"
"$(\"#sfAllBtn\").onclick=()=>{ if(confirm(\"Apply the save fix to every game that has a save library"
" in its fakelib\? You can undo it per game.\")) post(\"/api/savefix\?id=all\"); };\n"
"$(\"#moveBtn\").onclick=()=>queueSelected(\"move\");\n"
"$(\"#copyBtn\").onclick=()=>{ if(confirm(\"Copy keeps the original, so SMP will see two copies with "
"the same title ID. Continue\?\")) queueSelected(\"copy\"); };\n"
"$(\"#selNone\").onclick=()=>{ sel.clear(); renderBatch(); refresh.sig=null; refresh(); };\n"
"\n"
"(function loop(){ refresh().finally(()=>{ const busy=state&&state.queue.running; setTimeout(loop, bu"
"sy\?1500:4000); }); })();\n"
"</script>\n"
"</body>\n"
"</html>\n"
"";
