#!/usr/bin/env python3
"""gen_blob.py OUT.c NAME=FILE [NAME=FILE ...] -> C byte arrays.
A NAME with an empty FILE ("NAME=") produces an empty blob."""
import sys
out = ['/* generated by tools/gen_blob.py - do not edit */', '#include <stddef.h>']
for spec in sys.argv[2:]:
    name, _, path = spec.partition('=')
    data = open(path, 'rb').read() if path else b''
    out.append(f'const unsigned char {name}[] = {{')
    for i in range(0, len(data), 20):
        out.append('  ' + ','.join(str(b) for b in data[i:i+20]) + ',')
    if not data:
        out.append('  0')
    out.append('};')
    out.append(f'const size_t {name}_len = {len(data)};')
open(sys.argv[1], 'w').write('\n'.join(out) + '\n')
